---
- include_tasks: uninstall_old_docker.yml
- include_tasks: copy_source.yml

#- name: Install Docker
#  yum:
#    name: docker-ce-18.09.0
#    state: latest

- name: Start Docker
  service: 
    name: docker
    state: started
