---
- name: Check if docker is installed
  command: docker -v
  register: docker_installed_check
  ignore_errors: yes

- include_tasks: setup_repo.yml
  when: docker_installed_check is failed

- include_tasks: copy_source.yml
  when: docker_installed_check is failed

- include_tasks: install_docker.yml
  when: docker_installed_check is failed

- include_tasks: install_docker_compose.yml
  when: docker_installed_check is failed

- name: Start Docker
  systemd: 
    name: docker
    state: started
    enabled: yes

- name: Check docker swarm mode
  command: docker node ls
  register: docker_swarm_mode_check
  ignore_errors: yes

- name: Debug
  debug:
    msg: "Docker swarm: no"
  when: docker_swarm_mode_check is failed

- name: List all swarm node
  debug:
    msg: "{{ docker_swarm_mode_check.stdout_lines }}"
  when: docker_swarm_mode_check is changed
