---
- include_tasks: uninstall_old_docker.yml
- include_tasks: copy_source.yml
- include_tasks: install_docker.yml
- include_tasks: install_docker_compose.yml

- name: Start Docker
  service: 
    name: docker
    state: started
